config/routes.rb
Rails.application.routes.draw do
  resources :analyzers, only: :index
  resources :synonyms, only: :index
  resource :home, only: :show

  root 'home#show'

end

app/models/analyzer.rb
class Analyzer
  include ActiveModel::Model

  attr_accessor :id, :name, :description, :analyzer

  class << self
    def all
      cache.values
    end

    def find(analyzer_id)
      cache[analyzer_id]
    end

    private

    def cache
      return @cache if defined?(@cache)

      config = YAML.load_file(Rails.root.join('data', 'analyzers.yml'))
      @cache = config['analyzers'].each_with_object({}) do |(analyzer_id, details), memo|
        analyzer = Lucene::AnalyzerFactory.new(analyzer_id).build

        name = details['name']
        description = details['description']

        memo[analyzer_id] = new(id: analyzer_id, name: name, description: description, analyzer: analyzer)
      end
    end
  end

  # @return [Enumerable]
  #
  def tokenize(text)
    Lucene::Tokenizer.new(analyzer, text)
  end
end

app/controllers/analyzers_controller.rb
class AnalyzersController < ApplicationController

  helper_method :selected_analyzer_ids
  helper_method :all_analyzer_ids
  helper_method :all_analyzers

  def index
    if params[:text].blank?
      @analyzers = []
      render :index and return
    end

    @analyzers = selected_analyzer_ids.map do |analyzer_id|
      analyzer = Analyzer.find(analyzer_id)
      AnalyzerDecorator.new(analyzer, text: text)
    end
  end

  private

  def text
    params[:text]
  end

  def selected_analyzer_ids
    params[:analyzer_ids] || []
  end

  def all_analyzer_ids
    Analyzer.all.map(&:id)
  end

  def all_analyzers
    Analyzer.all
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def show; end
end

app/controllers/synonyms_controller.rb
class SynonymsController < ApplicationController

  def index
    if params[:synonyms].blank? || params[:text].blank?
      @tokens = []
      render :index and return
    end

    @tokens = SynonymExtractor.new(params[:synonyms], params[:text]).tokens
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/analyzers/_table.html.haml
%table
  %thead
    %tr
      %th Analyzer
      %th Tokens
  %tbody
    - analyzers.each do |tokenizer|
      %tr
        %td
          = tokenizer.name
        %td
          - tokenizer.each do |token|
            = token

app/views/analyzers/index.html.haml
.row
  %h1 Analyzer

.row.collapse
  = form_tag analyzers_path, method: 'get' do

    .row
      = label_tag :text, 'Text to Analyze'
      = text_area_tag :text, params[:text], required: true

    .row
      .small-12.medium-4.columns
        .row.analyzers
          %label Analyzers

          .row
            = check_box_tag 'analyzers_all', nil, selected_analyzer_ids == all_analyzer_ids, id: "analyzer_all"
            = label_tag "analyzer_all", 'All'

          - all_analyzers.each do |analyzer|
            .row.collapse.analyzer
              .small-1.columns
                = check_box_tag 'analyzer_ids[]', analyzer.id, selected_analyzer_ids.include?(analyzer.id), id: "analyzer_#{analyzer.id}"
              .small-11.columns
                = label_tag "analyzer_#{analyzer.id}" do
                  = analyzer.name
                  = '-'
                  %span.note= analyzer.description

        .row
          = button_tag 'Analyze', value: 'analyze'

      .small-12.medium-8.columns
        .row
          - if @analyzers.present?
            = render 'analyzers/table', analyzers: @analyzers

app/views/home/show.html.haml
.row
  %h2 Tools for Apache Lucene

.row
  .tools
    .tool
      = link_to 'Analyzer', analyzers_path
      = '-'
      Preview tokenization of several Analyzers built-in to Apache Lucene.
    .tool
      = link_to 'Synonyms', synonyms_path
      = '-'
      Preview Synonym replacement at index-time.

app/views/layouts/application.html.haml
!!! 5
%html{ :lang => "en"}
  %head
    %meta{ :charset => "utf-8" }

    %title lucene.me

    %meta{ :name => "viewport", :content => "width=device-width, initial-scale=1.0" }

    = stylesheet_link_tag "application"
    = javascript_include_tag "vendor/modernizr"
    = csrf_meta_tag

  %body

    %nav.top-bar{ 'data-topbar' => true }
      %ul.title-area
        %li.name
          %h1
            = link_to 'lucene.me', root_path
      %section.top-bar-section
        %ul.right
          %li.has-dropdown
            %a{ href: '#' } Tools
            %ul.dropdown
              %li
                = link_to 'Analyzer', analyzers_path

    = yield
    = javascript_include_tag 'application'

app/views/synonyms/index.html.haml
.row
  %h1 Synonyms

.row
  .small-12.medium-6.columns
    .row.collapse
      = form_tag synonyms_path, method: 'get' do

        .row
          = label_tag :synonyms
          = text_area_tag :synonyms, params[:synonyms]

        .row
          = label_tag :text
          = text_area_tag :text, params[:text]

        .row
          = button_tag 'Generate', value: 'generate'

  .small-12.medium-6.columns
    .row.collapse
      %label Tokens
      - if @tokens.present?
        - @tokens.each do |token|
          = "[#{token}]"
      - else
        Enter synonyms and text to get started.